---
title: "Воспроизводимые исследования с R"
author: "Boris Demeshev"
date: "`r format(Sys.time(), '%d.%m.%Y')`"
output: html_document
---

Ссылки:
-------
* [github-репозиторий](https://github.com/bdemeshev/rrr) курса
* [Заметки по R](http://bdemeshev.github.io/r_cycle/)
* Бакалаврский [курс эконометрики вшэ](http://bdemeshev.github.io/em301/)
* Как заставить R [сохранять пакеты в определённой папке](http://stackoverflow.com/questions/20440041/). Полезно для тех у кого под windows логин русскими буквами.
* [Видеозаписи лекций](http://www.youtube.com/playlist?list=PL1poMUvVlAqeH5DM0oowO4U7dQQ80CevV)

Материалы 2016
--------------
Занятия проходят по пятницам в 3231 на Шаболовке 26 с 18:10 до 21:00.


* [Семинар 10](https://github.com/bdemeshev/rrr/raw/master/scripts/sem_10_lasso.R): LASSO и гребневая регрессия

* [Семинар 9](https://github.com/bdemeshev/rrr/raw/master/scripts/sem_09_quant.R): Медианная, квантильная регрессия. Снова [r+markdown](https://github.com/bdemeshev/rrr/raw/master/scripts/sem_09.Rmd).

* Семинар 8: Rmarkdown, настройка

* [Семинар 7](https://github.com/bdemeshev/rrr/raw/master/scripts/sem_07.R): 
    - факторные переменные
    - [R + markdown](https://github.com/bdemeshev/rrr/blob/master/scripts/sem_07_demo.Rmd)

* [Семинар 6](https://github.com/bdemeshev/rrr/raw/master/scripts/sem_06.R): пакет `ggplot2`: универсальный подход к графикам

* [Семинар 5](https://github.com/bdemeshev/rrr/raw/master/scripts/sem_05.R): Анализ данных еге

* [Семинар 4](https://github.com/bdemeshev/rrr/raw/master/scripts/sem_04.R): пример решения практической задачи в R. Три способа посчитать границы для выбросов по каждой строке. Исходный [файл с данными](https://github.com/bdemeshev/rrr/raw/master/examples/%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80%20%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D1%8B%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85.csv).

* [Семинар 3](https://github.com/bdemeshev/rrr/raw/master/scripts/sem_03.R): загрузка данных (csv, excel и прочее). Сортировка, отбор переменных, отбор наблюдений, создание переменных. Длинные и широкие таблицы. Группировка и агрегирование данных: стратегия разделяй-властвуй и соединяй! Метод наименьших квадратов. Три уровня информации о модели (пакет `broom`).
    - пакет [reshape2](http://seananderson.ca/2013/10/19/reshape.html): длинные и широкие таблицы
    - пакет [dplyr](https://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html): базовые операции с табличками
    - что можно [достать из обычной регрессии](http://bdemeshev.github.io/r_cycle/cycle_files/02_ols_oranges.html)
    - пакет [broom](https://cran.r-project.org/web/packages/broom/vignettes/broom.html): стандартное представление результатов разных моделей

* [Семинар 2](https://github.com/bdemeshev/rrr/raw/master/scripts/sem_02.R) векторы, таблички с данными. Сортировка, отбор наблюдений, создание новых переменных. Синтаксис с использованием «трубочки» `%>%`.
* Семинар 1. Первая встреча, обсуждение тем, программы. На следующие занятия приносим свои ноуты: R, Rstudio, Latex.


